apiVersion: v2
appVersion: 2.0.0-alpha9
description: Hyperion is an opensource Bias or Ambient Lighting implementation
name: hyperion-ng
version: 0.0.1
upstream_version: 1.1.1
keywords:
  - hyperion-ng
  - hyperion
home: https://github.com/truecharts/truecharts/tree/master/charts/hyperion-ng
icon: https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/assets/webconfig/img/hyperion/hyperionlogo.png?raw=true
sources:
  - https://github.com/hyperion-project/hyperion.ng
  - https://hub.docker.com/r/sirfragalot/hyperion.ng
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0