apiVersion: v2
appVersion: version-v0.17.153
description: API Support for your favorite torrent trackers.
name: jackett
version: 1.4.0
keywords:
  - jackett
  - torrent
  - usenet
home: https://github.com/truecharts/charts/tree/dev/charts/jackett
icon: https://raw.githubusercontent.com/truecharts/truecharts/master/charts/jackett/icon.png?raw=true
sources:
  - https://github.com/Jackett/Jackett
  - https://hub.docker.com/r/linuxserver/jackett
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 0.12.2
