apiVersion: v2
appVersion: 0.39.0
description: Navidrome is an open source web-based music collection server and streamer
name: navidrome
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - navidrome
  - music
  - streaming
home: https://github.com/truecharts/truecharts/tree/master/charts/navidrome
icon: https://github.com/deluan/navidrome/blob/master/ui/src/icons/android-icon-72x72.png?raw=true
sources:
  - https://github.com/deluan/navidrome
  - https://hub.docker.com/r/deluan/navidrome
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0