apiVersion: v2
appVersion: 4.1.1
description: Flood is a monitoring service for various torrent clients
name: flood
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - flood
  - rtorrent
  - qbittorrent
  - transmission
home: https://github.com/truecharts/truecharts/tree/master/charts/flood
icon: https://raw.githubusercontent.com/jesec/flood/master/flood.svg
sources:
  - https://github.com/jesec/flood
  - https://hub.docker.com/r/jesec/flood
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0