apiVersion: v2
appVersion: v2.7.1
description: ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home
name: grocy
version: 0.0.1
upstream_version: 4.3.1
keywords:
  - grocy
home: https://github.com/truecharts/truecharts/tree/master/charts/grocy
icon: https://github.com/grocy/grocy/raw/master/public/img/appicons/mstile-150x150.png
sources:
  - https://github.com/grocy/grocy
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0