apiVersion: v2
appVersion: 2.0.1
description: Collect ALL UniFi Controller, Site, Device & Client Data - Export to InfluxDB or Prometheus
name: unifi-poller
version: 0.0.1
upstream_version: 5.2.1
keywords:
  - unifi
  - unifi-poller
home: https://github.com/truecharts/truecharts/tree/master/charts/unifi-poller
icon: https://raw.githubusercontent.com/wiki/unifi-poller/unifi-poller/images/unifi-poller-logo.png
sources:
  - https://github.com/unifi-poller/unifi-poller
  - https://hub.docker.com/r/golift/unifi-poller
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0
  - name: influxdb
    version: 1.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
