apiVersion: v2
appVersion: 2.7.2
description: Resilio Sync is a fast, reliable, and simple file sync and share solution, powered by P2P technology
name: resilio-sync
version: 0.0.1
upstream_version: 1.1.1
keywords:
  - resilio
  - sync
  - btsync
  - bittorrent
home: https://github.com/truecharts/truecharts/tree/master/charts/resio-sync
icon: https://blog.resilio.com/wp-content/uploads/2016/06/SyncSymbol-260x260px.png
sources:
  - https://github.com/orgs/linuxserver/packages/container/package/resilio-sync
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0