apiVersion: v2
appVersion: 2.1.2.0120
description: M3U Proxy for Plex DVR and Emby Live TV.
name: xteve
version: 0.0.1
upstream_version: 4.2.1
keywords:
  - xteve
  - iptv
  - plex
  - emby
home: https://github.com/truecharts/truecharts/tree/master/charts/xteve
icon: https://raw.githubusercontent.com/xteve-project/xTeVe/master/html/img/logo_b_880x200.jpg
sources:
  - https://xteve.de
  - https://github.com/xteve-project/xTeVe
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0