apiVersion: v2
appVersion: v2.0.3-2201906121747
description: Deluge is a torrent download client
name: deluge
version: 0.0.1
upstream_version: 1.1.1
keywords:
  - deluge
  - torrent
home: https://github.com/truecharts/truecharts/tree/master/charts/deluge
icon: https://avatars2.githubusercontent.com/u/6733935?v=3&s=200
sources:
  - https://hub.docker.com/r/linuxserver/deluge/
  - https://deluge-torrent.org/
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0