apiVersion: v2
appVersion: 4.0.8
description: Lychee is a free photo-management tool, which runs on your server or web-space
name: lychee
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - lychee
  - photo
  - pictures
home: https://github.com/truecharts/truecharts/tree/master/charts/lychee
icon: https://github.com/LycheeOrg/Lychee/blob/master/Banner.png?raw=true
sources:
  - https://github.com/LycheeOrg/Lychee
  - https://hub.docker.com/r/lycheeorg/lychee
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0