apiVersion: v2
appVersion: v2009.1.0
description: Booksonic is a platform for accessing the audibooks you own wherever you are
name: booksonic-air
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - booksonic
  - audiobook
home: https://github.com/truecharts/truecharts/tree/master/charts/booksonic-air
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/booksonic-air.png
sources:
  - https://github.com/popeen/Booksonic-Air
  - https://hub.docker.com/r/linuxserver/booksonic-air
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0