apiVersion: v2
appVersion: latest
description: TVheadend - a TV streaming server and digital video recorder
name: tvheadend
version: 0.0.1
upstream_version: 1.1.2
keywords:
  - tv
  - streaming
  - dvb
home: https://github.com/truecharts/truecharts/tree/master/charts/tvheadend
sources:
  - https://github.com/tvheadend/tvheadend
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0
