apiVersion: v2
appVersion: 0.4.20
description: pyLoad is a Free and Open Source download manager written in Python and designed to be extremely lightweight, easily extensible and fully manageable via web.
name: pyload
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - pyload
  - download
home: https://github.com/truecharts/truecharts/tree/master/charts/pyload
icon: https://github.com/pyload/pyload/blob/main/media/logo.png?raw=true
sources:
  - https://github.com/pyload/pyload
  - https://hub.docker.com/r/linuxserver/pyload
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0