apiVersion: v2
appVersion: 1.17.0
description: FreshRSS is a self-hosted RSS feed aggregator
name: freshrss
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - freshrss
  - rss
home: https://github.com/truecharts/truecharts/tree/master/charts/freshrss
icon: https://github.com/FreshRSS/FreshRSS/blob/master/docs/img/FreshRSS-logo.png?raw=true
sources:
  - https://github.com/FreshRSS/FreshRSS
  - https://hub.docker.com/r/linuxserver/freshrss
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0