apiVersion: v2
appVersion: 0.1.0.351
description: A fork of Radarr to work with Books & AudioBooks
name: readarr
version: 0.0.1
upstream_version: 1.1.1
keywords:
  - readarr
  - torrent
  - usenet
  - AudioBooks
  - ebooks
home: https://github.com/truecharts/truecharts/tree/master/charts/readarr
icon: https://readarr.com/img/logo.png
sources:
  - https://github.com/Readarr/Readarr
  - https://readarr.com
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0