apiVersion: v2
appVersion: latest
description: CouchPotato (CP) is an automatic NZB and torrent downloader.
name: couchpotato
version: 0.0.1
upstream_version: 4.3.1
keywords:
  - couchpotato
  - usenet
  - bittorrent
home: https://github.com/truecharts/truecharts/tree/master/charts/couchpotato
icon: https://github.com/CouchPotato/CouchPotatoServer/raw/master/couchpotato/static/images/icons/android.png
sources:
  - https://hub.docker.com/r/linuxserver/couchpotato/
  - https://github.com/CouchPotato/CouchPotatoServer/
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0