apiVersion: v2
appVersion: 0.4.2
description: Bot for Prometheus Alertmanager
name: alertmanager-bot
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - alertmanager
  - telegram
  - bot
  - alerting
home: https://github.com/truecharts/truecharts/tree/master/charts/alertmanager-bot
sources:
  - https://hub.docker.com/r/metalmatze/alertmanager-bot
  - https://github.com/metalmatze/alertmanager-bot
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0