apiVersion: v2
appVersion: 0.6.9
description: Calibre-Web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.
name: calibre-web
version: 0.0.1
upstream_version: 4.3.1
keywords:
  - calibre
  - ebook
home: https://github.com/truecharts/truecharts/tree/master/charts/calibre-web
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
sources:
  - https://hub.docker.com/r/linuxserver/calibre-web/
  - https://github.com/janeczku/calibre-web
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0