apiVersion: v2
appVersion: v3.8.1
description: Usenet meta search
name: nzbhydra2
version: 0.0.1
upstream_version: 5.3.1
keywords:
  - nzbhydra2
  - usenet
home: https://github.com/truecharts/truecharts/tree/master/charts/nzbhydra2
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
sources:
  - https://hub.docker.com/r/linuxserver/nzbhydra2
  - https://github.com/theotherp/nzbhydra2
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0