apiVersion: v2
appVersion: 3.9.1
description: Perl client used to update dynamic DNS entries for accounts on Dynamic DNS Network Service Providers
name: ddclient
version: 0.0.1
upstream_version: 2.3.1
keywords:
  - ddclient
  - dns
home: https://github.com/truecharts/truecharts/tree/master/charts/ddclient
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ddclient-logo.png
sources:
  - https://github.com/ddclient/ddclient
  - https://hub.docker.com/r/linuxserver/ddclient
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: file://../../../library/common/
    version: 0.4.0